#显示相关
fontScale = 1
fontThickness= 1
lineThickness=1

waitKeyTime = 1

#相机设置相关
cameraMode = huaray			#相机模式aobi/ty/multiAobi/multiTy/huaray/multiHuaray
cameraNum = 1
enableRgbImg                 = 0     #是否开启rgb相机，1-开启，0-关闭
enableIrImg = 0			#是否开启ir相机，1-开启，0-关闭
enableRegistrationDepth2Color = 0 #1-将深度图对齐至RGB图，0-将RGB图对齐至深度图
RgbCamExposureTime = 0  	#设置rgb相机曝光时间，-1代表采用默认值。aobi相机无单位，0-代表自动曝光。ty相机0-100，100代码33.3ms
RgbCamGain = 32		#设置rgb相机增益，-1代表采用默认值。现只支持ty相机，设置范围[0,255]
IrCamExposureTime = 33 	 	#设置ir相机曝光时间，-1代表采用默认值。aobi相机单位ms。ty相机0-100，100代码33.3ms
IrCamGain = -1			#设置ir相机增益，-1代表采用默认值。现只支持ty相机，设置范围[0,255]
validWidthPercent = 1		#相机深度图宽度方向上有效比例[0,1]，只对aobi相机有效
validHeightPercent = 1  	#相机深度图高度方向上有效比例[0,1]，只对aobi相机有效
useHardTrigger = 0		#是开启硬触发，0-FreeRun自由拉流，1-HardTrigger 硬触发Line1， 2-SoftTrigger 软触发，3-硬触发Line0，4-相机级联触发
MainCamID = 1           #华睿相机多相机模式下，选择相机级联触发时，需设置此项，根据硬件接线方式设置主相机的编号； 
triggerDelay = 50  	#软触发触发时间间隔，单位ms
enableSave = 0
enableSaveImage = 0
CamSmartMode   =1     #是否使用智能机模式,0-不开启，1-开启（测体积使用）
IsCalVol = 1     #是否为测体积，0-单件分离，1-测体积
calVolume_zjs = 1
timeSyncMode =1				#同步时间模式，0-自动同步，1-手动同步
timeSyncRate = 10000		#同步频率（ms）

#aobi相机背景 	0使用3DCfg/background.bin作为背景，要更新背景时，删掉该文件，在启动软件前清空台面即可
#				1自动更新背景，每次软件启动时把双目的第一帧作为背景
upadteBackground = 0

#huaray智能机 	多包检测模式 0关 1开
# 				多包、去手、叠件检测(视为不稳定体积)
SinglepackDetectionMode = 0
# 算法存图使能
enableSaveImageAlg = 0
# 存图路径
saveImageAlgPath = D:/Images
# 按绑定时间存图   0有包裹就存   1SDK返回时间戳，然后对照时间戳存 
saveImageByTime = 1
# 单相机序列号
cameraSN=

#算法检测方法，0-基于深度图像的图像处理方法，1-基于RGBD的图像处理方法，3-基于RGBD的深度学习方法，4-结合方法0和方法3
detectMethod = 0

#坐标范围限制 1-开启，0-关闭 开启后下面四个参数才生效
EnableAdjustPtOrder = 0 

#X 坐标范围最小值
RangeMinX = 0

#Y 坐标范围最小值
RangeMinY = 0

#X 坐标范围最大值
RangeMaxX = 2000

#Y 坐标范围最大值
RangeMaxY = 1500

#深度图稳定帧数
stableFrameNum = 1

#体积数据稳定帧数
volumeStableFrameNum = 1

#在稳定帧数volumeStableFrameNum内，每帧体积数据（长、宽、高）之间允许的最大偏差
volumeStableBia = 5

#是否开启去除手干扰功能，1-开启，0-关闭。开启该功能需要同时开启多帧稳定功能（即设置volumeStableFrameNum>1）,避免误切除导致出现非包裹体积
enableRemoveHandInterfer = 0

#深度图分辨率设置
cameraResolution                = 640x480

#工作距离
workDistance = 682

#显示物体中心可移动尺寸
objectCenterRegionSize = 5

#1去除与背景相交的物体，0不去除，只影响显示
enableRemoveObjectOfEdge = 01

#1显示深度图结果窗口，0不显示。关闭显示可提高输出体积频率
showResult = 01

#1显示实时更新的背景，0不显示
showBackground = 0

#最大测量高度
maxHeight = 450

#最小测量高度
minHeight = 15

#最小物体宽度
minWidth = 50

#最小物体长度
minLength = 50

#深度图采样因子
depthImgSampleFactor = 2

#深度图空洞填充尺寸
gapFillSize = 5

#体积计算时的轮廓平滑因子[0,1]
contoursSmoothFactor = 1

#体积计算方法，0-长*宽*高体积计算方法，1-只考虑物体顶面点云的积分体积计算方法（适用于相机垂直安装），2-考虑物体侧面点云的积分体积计算方法（适用相机能看到物体侧面点云的情况）
calVolumeMethod= 1

#深度图平滑尺寸
depthSmoothSize = 3

#1实时更新参考面，0固定参考面
updateRefPlane                 = 1

#参考面最少点数量
refPlaneMinPtNum = 1000

#参考面最大拟合误差
maxFitPlaneError = 5

#初始参考面搜索范围
initRefPlaneZRangeSize = 40

#参考面更新过程当中，新参考面点云的Z值搜索范围
updateRefPlaneZRangeSize                = 20

#参考面更新速度
refPlaneUpdateSpeed = 0.1


#背景采样因子
backgroundSampleFactor = 3

#背景更新时的允许差异高度，即与原先背景差异在该范围内的点才参与更新
updateBackgroundHeight = 30

#背景更新速度[0,1]
backgroundUpdateSpeed = 0.01

#y方向调整大小，在使用包围盒体积（长*宽*高）计算模式下有效
yAdjustSize = -0

#x方向调整大小，在使用包围盒体积（长*宽*高）计算模式下有效
xAdjustSize= -5

#高度调整大小，在使用包围盒体积（长*宽*高）计算模式下有效
heightAdjustSize= -0

#体积调整百分比率。例如，该值设置为1时，代表在原有体积的基础上增加1%
volumeAdjustPercentage = 0

#参考面高度调整尺寸。参考面高度上可能存在偏差，可通过该参数进行调整。例如，在平台上垫了一块10mm厚度的平板进行参考面标定，则该参数应当设置为-10
refPlaneHeightAdjustSize = 0

#算法运行模式，1-计算体积模式，2-检测包裹状态模式，3-定位包裹模式
calVolumeRunMode = 1

#体积计算模式下，是否存在托盘干扰，1-是，0-否
haveTray = 0

#存在托盘干扰情况下，托盘的高度
trayHeight = 0

#检测包裹状态模式下，粘连包裹的最小凸缺陷深度
minConvexDefectDepth = 50

#两个物体之间的最小间距，小于此距离的两个物体判为一个，判断两个物体是否粘连在一起
minObjectDistance = 100

#是否显示多体积，1-显示多体积，0-显示单体积
showMultiVolume = 1

#是否将物体位置变换至平台坐标系，1-是，0-否
transformObjectPosToPlatform = 0

#是否矫正相机朝向，1-矫正，0-不矫正。开启矫正功能需要预先标定参考平面。该功能用于相机倾斜安装的情况。
rectifyCameraDirection = 0

#包裹定位相关参数
localSegmentFiledSize = 30	#局部阈值分割物体时的局部尺寸，单位为mm
localSegmentThresh = 30 	#局部阈值分割物体时的局部尺寸，单位为mm

#实时保存点云数据的时间间隔，单位为秒，小于等0代表不实时保存点云数据
saveDataTimeInterval= 0

#单件分离器分离单元规格
separatorRowNum = 7					#行数
separatorColNum = 4					#列数
separatorRowSpace = 0				#行间距
separatorColSpace = 0				#列间距(运动方向)
separatorConveyerWidth = 600		#单个执行单元宽度(运动方向)
separatorConveyerHeight = 150		#单个执行单元高度
